---
- block:
    - name: "Ensure firewalld is available."
      ansible.builtin.package:
        name: "{{ gazellacom_firewalld_package }}"
        state: present

    - name: "Configure firewall for {{ gazellacom_app_port_firewalld }} ports"
      ansible.posix.firewalld:
        port: "{{ gazellacom_app_port_firewalld }}"
        permanent: true
        state: enabled
        immediate: yes
  become: true
